import {TonConnectUIProvider} from '@tonconnect/ui-react';
import type {Metadata} from 'next';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const manifestUrl = 'https://antochak.github.io/Ton-connect/public/manifest.json';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: manifestUrl,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        {/* <TonConnectUIProvider manifestUrl={manifestUrl}>{children}</TonConnectUIProvider> */}
        {children}
      </body>
    </html>
  );
}
